### PR TITLE
Folder multi

### PR DESCRIPTION
**Pull request by jennyfolkesson**
Hey @phoenixAja would you mind taking a look? Tests /imaging_db/images/tiffolder_splitter_tests.py are failing and I can't figure out why since the other splitter tests are working and uploading real data works. Tests also pass when running serialized_upload sequentially instead of with multiprocessing.
Right now it doesn't look like the test keys exist with moto when using multiprocessing...

### CODE REVIEW

**Comment by jennyfolkesson** [comment]
@phoenixAja It looks like moto doesn't work for multiprocessing so I mocked out the multiprocessing map function in order to get the tests to work. Would you mind reviewing?

**Comment by phoenixAja** [comment]
@jennyfolkesson yes 100%

**Comment by jennyfolkesson** [comment]
@phoenixAja thanks for reviewing! If you're ok with the changes, would you mind approving?

**Comment by jennyfolkesson** [comment]
Please do!

**Pull request merged**
